services:
  suruchi:
    container_name: century-suruchi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_DOMAIN_NAME: ${API_DOMAIN_NAME}
        NEXT_PUBLIC_PATH: ${NEXT_PUBLIC_PATH}
        CONTEXT: ${CONTEXT}

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: 2977
      HOSTNAME: 0.0.0.0

    ports:
      - "2977:2977"

    restart: unless-stopped