services:
  suruchi:
    container_name: century-suruchi
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - ./public:/app/public

    environment:
      NODE_ENV: production
      PORT: 2977
      HOSTNAME: 0.0.0.0

    ports:
      - "2977:2977"

    restart: unless-stopped